name = "Well Traveled"
license = "MIT"
licenselink = "https://github.com/mpaluchowski/hugo-well-traveled/blob/master/LICENSE"
description = ""
homepage = "http://travel.paluchowski.com/"
tags = ["blog"]
min_version = 0.17

[author]
  name = "Michał Paluchowski"
  homepage = "https://michal.paluchowski.com/"
